fdehau/tui-rs

- examples/barchart.rs
- examples/block.rs
- examples/canvas.rs
- examples/chart.rs
- examples/gauge.rs
- examples/list.rs
- examples/paragraph.rs
- examples/sparkline.rs
- examples/table.rs
- examples/tabs.rs
Some examples panicked when the terminal was resized. The canvas example also panicked when the *ball* hit the border of the canvas.
> fixes panic when terminal was resized

- README.md
This is a small change, but it was a bit confusing for me when I was evaluating if this repository could do what I want. I did not realize cargo could run examples until now, and I also couldn't figure out how to quit the example while it was running (I was trying things like Ctrl-C).
> add note to readme about running/quitting examples

- src/layout.rs
Noticed that I need to call `.clone()` when I try to do something like pass in a variable of type `Direction` into a function call. Hope this is reasonable.
> Add Copy trait for layout enums

- Cargo.toml
- examples/paragraph.rs
- src/lib.rs
- src/style.rs
- src/widgets/paragraph.rs
I needed this functionality for a project I'm working on and thought it made sense to implement it in the widget itself.
The multipeek implementation is taken from itertools to avoid pulling it as a dependency.
Word wrap seems to work.
I have not tested this implementation with fancy unicode characters.
Failed travis is due to formatting errors in other files, I did not touch.
> Text alignment option for paragraph widget

- src/widgets/chart.rs
Consider the following code. Notice that the dataset passed in to the chart does not set an explicit `name` property.
```
Chart::default()
.block(Block::default().title("Plot").borders(Borders::ALL))
.x_axis(Axis::default()
.title("X")
.bounds([0.0, 1.0])
.labels(&[
"0",
"1",
]))
.y_axis(Axis::default()
.title("Y")
.bounds([0.0, 1.0])
.labels(&[
"0",
"1",
]))
.datasets(&[Dataset::default()
.marker(Marker::Braille)
.style(Style::default().fg(Color::Magenta))
.data(&vec![(0.0, 0.0), (1.0, 1.0)])
])
.render(t, &chunks[0]);
```
This code causes a chart to render like this:
By checking that the maximum length of a dataset name is above 0, we avoid rendering the legend when there is no dataset name.
After this fix is applied, the above code renders like this:
> fix(widgets): Prevent chart legend from rendering when no dataset has a name

- examples/demo.rs
- examples/list.rs
- examples/paragraph.rs
- examples/user_input.rs
- src/widgets/list.rs
- src/widgets/mod.rs
- src/widgets/paragraph.rs
I took a crack at fixing issue #70 and here's what it looks like. The slightly annoying thing is having to add `.into()` when building a `Text`. If that's too annoying we can maybe add some helper methods like `Text::data()` and `Text::styled_data()` that would do the conversion for you.
> Make Text accept both borrowed and owned strings

- examples/rustbox.rs
- src/backend/crossterm.rs
- src/backend/rustbox.rs
- src/backend/termion.rs
- src/backend/test.rs
- src/layout.rs
- tests/size.rs
This pull request can be also interpreted as a reason to reconsider using `u32` or `usize` for dimensions. Even then, checking for overflow won't hurt.
Demo: https://streamable.com/iqxi7 (max area reduced from max u16 to 5000 for demo purposes)
> Limit Rect size to prevent u16 overflow

- examples/barchart.rs
- examples/block.rs
- examples/canvas.rs
- examples/chart.rs
- examples/crossterm.rs
- examples/custom_widget.rs
- examples/demo.rs
- examples/gauge.rs
- examples/layout.rs
- examples/list.rs
- examples/paragraph.rs
- examples/sparkline.rs
- examples/table.rs
- examples/tabs.rs
- examples/user_input.rs
- src/terminal.rs
It basically never makes sense to render without syncing the size.
Without resizing, if shrinking, we get artefacts. If growing, we may get
panics (before this change the Rustbox sample (the only one which didn't
handle resizing on its own) panicked because the widget would get an
updated size, while the terminal would not).
> Feature: Autoresize

- src/backend/crossterm.rs
- src/backend/termion.rs
Otherwise, if the first update is to (1, 0) then no goto occurs. Something like this reproduces the error, producing "Playause" on the second update.
```rust
use termion::raw::IntoRawMode;
use tui;
use tui::widgets::Widget;
fn main() -> Result<(), failure::Error> {
let stdout = std::io::stdout().into_raw_mode()?;
let stdout = termion::screen::AlternateScreen::from(stdout);
let backend = tui::backend::TermionBackend::new(stdout);
let mut terminal = tui::Terminal::new(backend)?;
let size = terminal.size()?;
for i in ["Play", "Pause"].iter() {
terminal.draw(|mut f| {
let line = [tui::widgets::Text::raw(i.clone())];
tui::widgets::Paragraph::new(line.iter()).render(&mut f, size);
});
std::thread::sleep(std::time::Duration::from_millis(1000));
}
Ok(())
}
```
> Make sure we always emit a cursor goto for the first update.

- examples/paragraph.rs
- src/buffer.rs
- src/widgets/mod.rs
- src/widgets/paragraph.rs
- src/widgets/reflow.rs
- tests/paragraph.rs
There's a bunch of things to improve and test cases to add. LineWrapper is also ugly but I'll be making it prettier when I have tests.
The LineComposer trait implementations cannot be iterators because we attempt to be efficient so we only yield slices of the current line which lives only one "iteration".
The changeset doesn't modify the public API, however the behaviour of `.wrap(true)` has been changed to do wrapping on word boundaries. Since I used runtime polymorphism, we could allow users to inject their own wrapping logic but the interface is ugly (consumes and passes Style), so I'd keep it private.
We may want to reintroduce opt-in previous behaviour of wrapping regardless of previous behaviour but this would require to make `.wrap` take an enum.
> Paragraph - line wrapping on word boundaries

- src/widgets/tabs.rs
and don't show divider after last tab.
**_Short reminder:_** Before this PR we had the following:
Now we can do something like the following examples...
```rs
Tabs::default()
.block(Block::default().title("Tabs").borders(Borders::ALL))
.titles(&["Tab0", "Tab1", "Tab2", "Tab3"])
.style(Style::default().fg(Color::White))
.highlight_style(Style::default().fg(Color::Yellow));
```
```rs
Tabs::default()
.block(Block::default().title("Tabs").borders(Borders::ALL))
.titles(&["Tab0", "Tab1", "Tab2", "Tab3"])
.style(Style::default().fg(Color::White))
.highlight_style(Style::default().fg(Color::Yellow));
.divider(DOT);
```
```rs
Tabs::default()
.block(Block::default().title("Tabs").borders(Borders::ALL))
.titles(&["Tab0", "Tab1", "Tab2", "Tab3"])
.style(Style::default().fg(Color::White)) …
```
> Add `divider` for `Tabs`

- CHANGELOG.md
- examples/canvas.rs
- examples/demo.rs
- src/widgets/canvas/line.rs
- src/widgets/canvas/mod.rs
- src/widgets/canvas/rectangle.rs
This currently depends on #106 and fixes #87.
Renaming `Line` to `LineShape` is for consistency with `BoxShape` as I couldn't just call it `Box` and `Rect` is already in use. Also, there are already other uses of `Line` in this library so it would be helpful to disambiguate those too.
> Add new shape: Rectangle

- src/backend/crossterm.rs
Added the ability to create the crossterm backend with a previously created screen. This will allow the API user to specify whether they want to enter into raw mode and perform any prior setup on the crossterm end before passing off to tui.
> Create Crossterm Backend with Previously Created Screen

- examples/crossterm_demo.rs
- src/backend/crossterm.rs
`CrosstermBackend` currently does not allow alternate screen mode where we return to the original screen once we're done. #125 doesn't seem to fix this because we can't move a screen out of [AlternateScreen](https://docs.rs/crossterm/0.6.0/crossterm/struct.AlternateScreen.html) because of `Drop` (see [this](https://github.com/TimonPost/crossterm/issues/74) crossterm issue). This PR adds the required methods to `CrosstermBackend` and adds `crossterm_demo.rs` as an example.
> Add alternate screen mode to crossterm backend

- Cargo.toml
This is a follow-up to #153.
Since `crossterm 0.9` version development is still in progress (as an example, see [this bug](https://github.com/TimonPost/crossterm/issues/141)), forcing to use one specific version is a little bit excessive, so this PR relaxes `crossterm` version to `^0.9`.
@TimonPost confirmed that `crossterm` adheres to semantic versioning, therefore version can be relaxed safely.
As an addition, I removed the `crossterm_backend` feature because of two reasons:
1. `crossterm` feature is exists already (because `crossterm` as a depedency is optional)
2. Code that introduces it was merged into master 6 hours ago (at the time of creating this PR) and was not published yet, therefore possibility of breaking something is really small.
P.S. I have personal request also - can …
> Relaxing crossterm dependency version

- src/widgets/mod.rs
I know using clone isn't the best practice, but in some cases it can be extremely convenient. I'm working on a project where I'm doing quite a dance to get around it. In the end I wondered why I wasn't using clone and the answer wasn't obvious.
Am currently using a local fork with this in the meantime.
> Provide Clone and Debug for Text type

- src/widgets/tabs.rs
This PR fixes the highlight behavior of `Tabs`. Currently the divider after the current selection is highlighted as well as the selection, which seems unintended to me. Feel free to close if it's not.
Before:
After:
> Don't highlight Tabs divider after selection

- src/backend/crossterm.rs
Crossterm reports terminal size in terms of the maximum row/column _index_, as opposed to the _count_ of rows/columns.
Also updated the color mapping, as DarkGrey now exists in crossterm.
> Fix crossterm terminal size and dark gray color

- src/backend/curses.rs
The `get_cursor` and `set_cursor` methods for the curses backend invert rows and columns, this fixes things.
> Fix curses backend cursor positions

- src/widgets/canvas/mod.rs
- tests/chart.rs
In certain edge cases (like the test case provided in `tests/chart.rs`) a canvas can cause a panic. This change tests for this edge case and includes a regression test for the future.
> fix for canvas rendering edge cases causing overflow errors

- Cargo.toml
- examples/crossterm_demo.rs
- src/backend/crossterm.rs
I have been working on improving the performance of crosterm. The status can be followed here:https://github.com/TimonPost/crossterm/pull/175.  On windows, the performance increased with 60% and on Linux, the performance increased with +- 40% . 
This is positive for TUI, and now there are no glitches anymore in the screen. 
Before:
After
The noticeable change is, especially in the windows implementation. Windows is way slower with terminal actions. Like I had a benchmark where I did some stuff on windows it took 5 seconds to complete and on Linux it took less than one second.
For now, this should not be merged yet. I am still working on it, and once crossterm 0.10 releases I will update this PR as well.
> Crossterm Performance Update

- src/lib.rs
The usage instructions currently tell users to install `0.5` while `0.6` is the latest version. This fixes that
> Update docs to point to latest version

- src/widgets/chart.rs
This actually uses the set axis title style when drawing the chart widget. Until now the axis style was used.
> Fix: title_style was not used to style the axis title

- src/symbols.rs
An intersecting column and row where the row is not at the top or bottom intersect as a cross, the symbols::line module has every other intersection of the line so it makes sense that this should be added as well. 
Attached is my use case for this. Notice the cross symbol highlighted in red.
> Added a verticle 'cross' to the symbols as it was missing

- examples/block.rs
- src/symbols.rs
- src/widgets/block.rs
- src/widgets/mod.rs
This PR will implement a Blocky trait that defines the methods needed for drawing a block. There are three block types: Block, RoundedBlock, and DoubleBlock. The only differences are the unicode characters used to draw the borders. The RoundedBlock and DoubleBlock structs and methods will only be implemented when user applies the "rounded" and "double" features. This could avoid complicating things if simplicity is the goal.
> Rounded corners and Double line borders

- src/style.rs
- tests/paragraph.rs
Fix #223.
I tested the changes with the following snippet, just to verify that the changes actually enabled the use
of `const FOO: Style...`. Since the test is quite useless I removed them from the PR.
```rust
#[cfg(test)]
mod tests {
use super::*;
const RED: Color = Color::Red;
const RED_STYLE: Style = Style::new().fg(RED);
const RED_DIMMED: Style = Style::new()
.fg(Color::Red)
.bg(Color::Blue)
.modifier(Modifier::DIM);
#[test]
fn test_const() {
assert_eq!(RED, Color::Red);
assert_eq!(
RED_STYLE,
Style {
fg: Color::Red,
..Style::default()
}
);
assert_eq!(
RED_DIMMED,
Style {
fg: Color::Red,
bg: Color::Blue,
modifier: Modifier::DIM,
}
);
}
}
```
> Mark Style::* functions `const`

- README.md
Using `tui-rs` as been great and I'd like to add my app zenith to the `Apps using Tui` section.
> Add zenith to apps using tui

- src/widgets/table.rs
It is possible to use associated types the same way as generics parameters. In fact associated types are nothing more than better organized generics params. For example, there is no need to introduce another param to constraint iterator item to be Display, you can just say `where I::Iterator, I::Item: Display`. This allows to drop type params for Table from 5 to 2.
> Clean redundant generics params in Table

- README.md
Thank you for developing this project!
I've created [`oha`](https://github.com/hatoo/oha) which is using `tui-rs`.
I'd like to add `oha` to the `Apps using tui` section.
> Add `oha` to the "apps using tui" list

- examples/canvas.rs
- examples/chart.rs
- examples/demo/ui.rs
- src/layout.rs
- src/widgets/canvas/line.rs
- src/widgets/canvas/map.rs
- src/widgets/canvas/mod.rs
- src/widgets/canvas/points.rs
- src/widgets/canvas/rectangle.rs
- src/widgets/chart.rs
* Update the `Shape` trait. Instead of returning an iterator of point, all
shapes are now aware of the surface they will be drawn to through a `Painter`.
In order to draw themselves, they paint points of the "braille grid".
* Rewrite how lines are drawn using a common line drawing algorithm (Bresenham).
fix #232
> refactor(canvas): update shape drawing strategy

- src/widgets/list.rs
The code that outputs the list elements uses the full inner width of its
block, without taking the width of the highlight symbol into
consideration. This allows the elements to overflow the box and draw
over the block's border. To fix that, we need to reduce the target width
for the list elements.
> fix(widgets/list): fix line length calculation for selectable lists

- Cargo.toml
With this, the `documentation` link should also appear in the search result page of `crates.io` when searching for `tui`.
> add documentation field

- src/widgets/canvas/line.rs
- tests/chart.rs
Fix for underflow bug when using line generation: https://github.com/fdehau/tui-rs/issues/280
> Add bounds check when drawing line high/low

- src/widgets/canvas/line.rs
- src/widgets/chart.rs
- tests/chart.rs
Two things:
1.  Minor thing that I noticed when using this function.  Seems to look fine in documentation, but looked weird on stuff like VS Code.
2.  When using `GraphType::Line`, if the dataset is empty, you can end up with a subtraction underflow when you do the length - 1.
> docs: Fix missing code block fence for hidden_legend_constraints

- .github/workflows/ci.yml
- Makefile
- examples/block.rs
- examples/curses_demo.rs
- examples/custom_widget.rs
- examples/demo/app.rs
- examples/layout.rs
- examples/paragraph.rs
- examples/popup.rs
- examples/rustbox_demo.rs
- examples/table.rs
- examples/tabs.rs
- examples/user_input.rs
- examples/util/event.rs
- examples/util/mod.rs
- src/lib.rs
- tests/chart.rs
- tests/list.rs
- Remove deny warnings in lib.rs. This allows easier iteration when developing
new features. The warnings will make the CI fails anyway on the clippy CI
stage.
- Run clippy on all targets (including tests and examples) and all features.
- Fail CI on clippy warnings.
> chore: enable clippy on all targets and all features

- examples/crossterm_demo.rs
> feat(examples): enable mouse capture to make crossterm demo on par with termion

- src/layout.rs
This allows for layouts to be saved and reused and does not require an additional clone
> Borrow layout for splitting instead of moving it

- src/layout.rs
I implemented a Cassowary constraint solver in Go (which may be found [here](https://github.com/lithdew/casso)) and re-wrote `split()` in Go for vertical layouts just as a test case [here](https://gist.github.com/lithdew/250fde08aa4e08ce4211f74365268e17).
I got better numerical stability by constraining the width and heights of elements to be >= 0. Take for example the input:
```go
{
input: Rect{x: 2, y: 2, w: 10, h: 10},
params: []Constraint{Percentage(10), Max(5), Min(1)},
expected: []Rect{
{x: 2, y: 2, w: 10, h: 1},
{x: 2, y: 3, w: 10, h: 5},
{x: 2, y: 8, w: 10, h: 4},
},
}
```
Without the patch in this PR, I got malformed regions.
The third `Rect` in the output below is of height 10, which is as a result of the constraint solver erroneously positioning the third rectangle to overlap …
> Constrain width and height to be non-negative in split().

- src/style.rs
Add `StyleDiff` that may be used in a context where we want to use an existing `Style` as a base for an other one. The more telling example at the moment is the highlighting behavior upon selection in several widgets. In this case, users may want to change only a single property of the current item style instead of overriding it completely.
> Style diff

- CHANGELOG.md
- Cargo.toml
- examples/barchart.rs
- examples/block.rs
- examples/canvas.rs
- examples/chart.rs
- examples/crossterm_demo.rs
- examples/curses_demo.rs
- examples/custom_widget.rs
- examples/gauge.rs
- examples/layout.rs
- examples/list.rs
- examples/paragraph.rs
- examples/popup.rs
- examples/rustbox_demo.rs
- examples/sparkline.rs
- examples/table.rs
- examples/tabs.rs
- examples/termion_demo.rs
- examples/user_input.rs
- src/lib.rs
- src/terminal.rs
- src/widgets/mod.rs
- tests/widgets_block.rs
- tests/widgets_chart.rs
- tests/widgets_gauge.rs
- tests/widgets_list.rs
- tests/widgets_paragraph.rs
- tests/widgets_table.rs
- tests/widgets_tabs.rs
This implements the idea I outlined in https://github.com/fdehau/tui-rs/issues/91#issuecomment-634998916:
> can't `Frame` have a field like `Option<(u16, u16)>`, which is the cursor's desired position after drawing the frame? `None` means the cursor is hidden, `Some` with a position means the cursor is shown and is positioned at the given cell.
The implementation deviates from the idea in two ways.
First of all, `Frame` is moved into the drawing closure — there is no way for `Terminal::draw()` to examine frame's fields afterwards. This could be resolved in two ways:
1. make `Terminal::draw()` require `FnOnce(&mut Frame<B>)`. This is very clean, but it's a breaking change, so I decided against that.
2. store that `Option<(u16, u16)>` in the `Terminal` itself, and make `Frame` just pass the …
> Control cursor position and visibility via Frame

- README.md
There was a very small typo in the README on line 40, which cited the
`examples` folder as `exmples`. This resolves that issue.
> fix(readme): typo in demo section 

- examples/paragraph.rs
- src/widgets/paragraph.rs
- src/widgets/reflow.rs
- tests/widgets_paragraph.rs
Now Paragraph can scroll horizontally
```rust
let p = Paragraph::new(items)
.block(
Block::default()
)
.scroll((0, 7));
```
```
+------------------------------+
|hello world                   |
+------------------------------+
```
```
+------------------------------+
|orld                          |
+------------------------------+
```
> Add scroll horizontally support for paragraph

- examples/demo/ui.rs
- examples/paragraph.rs
- examples/popup.rs
- src/widgets/mod.rs
- src/widgets/paragraph.rs
- src/widgets/reflow.rs
- tests/widgets_paragraph.rs
Thanks for the wonderful library! :heart: 
I ran into some unexpected behaviour recently when I was attempting to print a paragraph with some indentation in wrapping mode – TUI was stripping the leading whitespace from my lines.
I've since discovered that this is an intentional behaviour, but that leaves me **unable** to print a paragraph like this:
```
MW Word of the Day                                                            
*verb*                                                                        
1) to diffuse through or penetrate something                               
2) to spread or diffuse through                                            
3) to pass through the pores or interstices of
```
In this PR, I simply disabled this behaviour, as I feel it's more predicable.
The …
> Preserve Indentation of Unwrapped Lines

- .github/workflows/ci.yml
- README.md
- Add section to README
- Run ci tests with this min version in addition of stable to track changes that would require a min
rustc version bump.
> chore: document rustc min version supported

- src/lib.rs
- src/terminal.rs
There was now way to avoid the autoresize behavior of `Terminal`. While it was fine for most users,
it made the testing experience painful as it was impossible to avoid the calls to `Backend::size()`.
Indeed they trigger the following error: "Inappropriate ioctl for device" since we are not running
the tests in a real terminal (at least in the CI).
This commit introduces a new api to create a `Terminal` with a fixed viewport.
> feat(terminal): add unstable api to use a fixed viewport

- .github/workflows/ci.yml
- CHANGELOG.md
- src/backend/crossterm.rs
- src/backend/termion.rs
- tests/backend_termion.rs
Both termion and crossterm backends were not moving the cursor if the first diff to draw was on the
second cell. The condition triggering the cursor move has been updated to fix this. In addition, two
tests have been added to avoid future regressions.
> fix(backend): move the cursor when first diff is on second cell

- src/backend/crossterm.rs
> Support more style modifiers on Windows and fix build with Crossterm 0.17.8

- src/symbols.rs
- src/widgets/canvas/mod.rs
this allows for clearer colors than using Dot, especially when
decreasing the size of the terminal font in order to increase the
resolution of the canvas
the reason I think this can be useful, is here:
Before:
After:
These two images have the same resolution (font is the smallest in my terminal) but blocks will show more color than dots
I'm not sure why, but I'm trying to port my emulator UI to TUI, which is very cool
> feat: added type Block in canvas markers

- README.md
Hi! 
I made [termchat](https://github.com/lemunozm/termchat) using `tui-rs`. I added it to the "apps using tui" list, but feel free to consider if it should be there because it seems simpler than the rest of the applications of the list.
Thank you for your effort in building `tui`!
> Add termchat to "apps using tui"

- src/backend/test.rs
When working on my other PR, I found a couple of places that `cargo clippy` was complaining about using `push_str` for the single `\n` character. I just applied the suggested solution. Up to you if this is important enough to merge or not :)
> A couple of trivial clippy fixes

- src/terminal.rs
- src/text.rs
This PR:
- Makes the `Text` constructors consistent with `Span` (adds `raw` and `styled`)
- Adds a `From<String>` implementation for `Text`
- Adds an `IntoIterator` implementation for `Text` (this is mainly for the `Extend` implementation, but it also means one can use `for` loops to iterate over the `Spans` of a `Text` object.
- Adds an `Extend` implementation for `Text`
This addresses #339 in a more thoughtful way than my last PR. To borrow a doctest from `Text` and show off the extension:
```rust
use tui::text::Text;
let mut text = Text::from("The first line\nThe second line");
assert_eq!(2, text.height());
text.extend(Text::raw("These are two\nmore lines!");
assert_eq!(4, text.height());
```  
There is obviously no documentation in this PR, as I don't know if this is an acceptable …
> Extend `Text` to be stylable and extendable

- src/widgets/barchart.rs
- tests/widgets_barchart.rs
Determination of how filled the bar should be was incorrectly taking the
entire chart height into account, when in fact it should take height-1, because
of extra line with label. Because of that the chart appeared fuller than it
should and was full before reaching maximum value.
> Fix barchart incorrectly showing chart filled more than actual

- Cargo.toml
- src/lib.rs
Crossterm v0.18 reduces the amount of dependencies, among other improvements. I couldn't detect a breaking [change](https://github.com/crossterm-rs/crossterm/blob/master/CHANGELOG.md).
> Upgrade crossterm to v0.18

- src/widgets/table.rs
- tests/widgets_table.rs
Percentage and ratio constraints don't take borders into account, which causes
the table to not be correctly aligned. This is easily seen when using 50/50
percentage split with bordered table. However fixing this causes the last column
of table to not get printed (see the failing test case), so there is probably another 
problem with columns width determination.
@fdehau could you take a look and see if you agree?
> Fix percentage and ratio constraints for table to take borders into account

- src/widgets/list.rs
While writing tests for my application I found it made things _a lot easier_ if I added `PartialEq` to `ListItem`. This way I can run assertions with an expected `Vec<ListItem>` against those that my app returns to verify everything is working correctly.
> feat(widgets/listitem): derive PartialEq

- src/widgets/block.rs
- tests/widgets_block.rs
Allow `Block` to render on areas where the height or the width is 1.
> fix(widgets/block): allow Block to render on small areas

- tests/backend_termion.rs
This fixes the clippy warnings that where introduced (see https://github.com/rust-lang/rust-clippy/issues/6026)
> Fix clippy warnings

- examples/list.rs
Hi :)
First of all, thanks for providing this crate! I'm really looking forward to build stuff with it :) 
This PR only adds some comments to the `list` example. Hopefully, this will make it easier for new people to understand those.
The example code is sometimes a little overwhelming, when one only wants to get a brief overview on how the library works, without deepdiving into the docs.
On top of that, this fixes the flow direction of the event list (it was previously going from 26 to 1)
> Add comments to "list" example and fix list direction

- src/widgets/table.rs
- tests/widgets_table.rs
If table rows are empty, it does not render at all.
I would expect header and empty border to be rendered.
> Draw table header and border even if rows are empty

- Cargo.toml
- examples/crossterm_demo.rs
- src/lib.rs
Related [CHANGELOG](https://github.com/crossterm-rs/crossterm/blob/master/CHANGELOG.md#version-019) entries for 0.19.
> Update crossterm to 0.19

- README.md
We use `tui-rs` for our [`vector top`](https://vector.dev/docs/reference/cli/#top) feature
> Add Vector to list of projects using tui-rs

- src/backend/test.rs
The occurrence of `panic!(debug_info)` was causing a compile warning, and will be a hard error in Rust 2021 edition.
This commit fixes the issue.
> Fix compile warning in test.rs

- src/backend/test.rs
The `TestBackend::clear` function didn't actually do anything before.  This feature changes it to clear the buffer.
I ran into this because I'm testing my full application (instead of just specific widgets), and switching between screens (which have `terminal.clear()` calls in between) was leaving junk on the screen.
> Actually clear buffer in TestBackend::clear

- src/text.rs
- src/widgets/table.rs
This is useful when you have a list of `Cow<str>` and you want to use it in a Row.
> feat(Text): Add a From<Cow<str>> impl for Text

- examples/block.rs
- src/widgets/block.rs
- tests/widgets_block.rs
This is PR for https://github.com/fdehau/tui-rs/issues/450
- Added title_alignment field to block struct
- Added title_alignment() method to set title_alignment of the block
- Added comments and title alignment to the example/block.rs
- Added tests for title alignment in tests/widgets_block.rs
- Added tests in srs/block.rs for inner
For all above, used layout::Alignment enum as the type for title_alignment.
> Added feature to align title of the block

- examples/user_input.rs
- examples/util/event.rs
The thread spawned by `Events` to listen for keyboard inputs had knowlegde of
the exit key to exit on its own when it was pressed. It is however a source of
confusion (#491) because the exit behavior is wired in both the event handler
and the input handling performed by the app. In addition, this is not needed as
the thread will exit anyway when the main thread finishes as it is already the
case for the "tick" thread. Therefore, this commit removes both the option to
configure the exit key in the `Events` handler and the option to temporarily
ignore it.
Close #491
> refactor(examples): remove exit key from Events handler

- src/lib.rs
A missing "and" after "an" (which I do all the time) and some tense clarification for some of the docs
no testing should be needed
> Fix minor grammatical errors in docs

- README.md
Add [gpg-tui](https://github.com/orhun/gpg-tui) to the [apps-using-tui](https://github.com/fdehau/tui-rs/#apps-using-tui) list.
> docs: add gpg-tui to the "apps using tui" list

- examples/gauge.rs
- src/widgets/gauge.rs
- tests/widgets_gauge.rs
Refactor the gauge render logic to fix two bugs:
* the label style was not applied
* using a label larger than the gauge width triggered a panic
Close #480 
* Two integration tests have been added
* Run `cargo run --example gauge`
> fix(widgets/gauge): apply label style and avoid overflow on large labels

- src/widgets/chart.rs
- src/widgets/list.rs
- src/widgets/table.rs
- tests/widgets_chart.rs
* clamp the width of the first x axis label to not go above the width between the chart left border and the y axis.
* clamp the width of all other x axis labels to not go above the width between each x axis tick.
* clamp the width of all y axis labels to not go above 1/3 of the chart area.
Fixes #490
> fix(widgets/chart): remove panics with long axis labels

- src/layout.rs
- src/widgets/table.rs
- tests/widgets_table.rs
The sum of the columns widths returned by `Table::get_column_widths` can sometimes be greater than the available width. This is happening because we are not feeding enough constraints to the `cassowary` solver. At the same time we already have an abstraction over `cassowary` which is used everywhere else: `Layout`. Therefore, I've replaced the manual column widths computation by a call to `Layout`.
Fixes https://github.com/fdehau/tui-rs/issues/470
A regression test provided in #508 was used to test the solution.
> fix(widgets/table): improve computation of table column widths

- src/widgets/list.rs
- src/widgets/table.rs
- tests/widgets_list.rs
- tests/widgets_table.rs
Avoid panics in `Table` and `List` when the input rows or items are shortened between two frames and the previous offset is now out of bounds.
> fix(widgets): avoid offset panic in `Table` and `List` when input changes

- examples/table.rs
Third column in table example was using the `Max` constraint.
But since version 0.16, the layout system does not add a hidden constraint on the last column which would ensure that it fills the remaining available space (a change that was already mentioned in #525). In addition, `tui` does not support sizing based on content because of its immediate mode nature. Therefore, `Max` is now resolved to `0`. Replacing with `Min` fixes the issue.
A new way of specifying constraints is being worked on at #519 which should for more deterministic and advanced layout.
Fixes #561 
```
cargo run --example table
```
> chore: fix table example

- Cargo.toml
Seems like a typo; this can cause features to not compile as expected.
> Correct the TOML

- src/widgets/chart.rs
- tests/widgets_chart.rs
This PR allows users to customize the alignment of the chart widget's axis' labels.
It implements a solution of the issue #567.
The alignment can be customized through the new method `Axis::labels_alignment(alignment: Alignment)`:
```rust
let axis = Axis::default()
.labels([Span::from("0"), Span::from("100")])
.labels_alignment(Alignment::Right);
```
By default, the alignment of an `Axis` is `Alignment::Left`.
This produces an output similar to the one currently produced.
Defining the alignment of the Y axis will affect the position of all Y-axis labels.
Defining the alignment of the X axis will only affect the position of the first label, relative to the Y-axis.
A side-effect of the PR is that X-axis labels are now closer to their correct position.
Currently on the  branch `master`:
With …
> Chart axis alignment

- Cargo.toml
Updates `crossterm` to the latest version, see [`crossterm`'s changelog](https://github.com/crossterm-rs/crossterm/blob/master/CHANGELOG.md#version-023). (Personally, I'm just wanted to get rid of an outdated dependency warning in one of my projects lol.)
Builds, no clippy lints
`cargo make ci` fails, but this also happens without `crossterm` being updated (below is run on `master`):
```
error: single-character string constant used as pattern
--> src\widgets\reflow.rs:492:39
|
492 |         let text_space = text.replace("\u{00a0}", " ");
|                                       ^^^^^^^^^^ help: try using a `char` instead: `'\u{00a0}'`
|
= note: `-D clippy::single-char-pattern` implied by `-D warnings`
= help: for further information visit …
```
> Update crossterm to v0.23

- Cargo.toml
- examples/panic.rs
Without a terminal-resetting panic hook there are two main problems when an application panics:
1.  The report of the panic is distorted because the terminal has not properly left the alternate screen and is still in raw mode.
2.  The terminal needs to be manually reset with the `reset` command.
To avoid this, the standard panic hook can be extended to first reset the terminal. That's what this new example showcases.
```
cargo run --example panic
```
* ~~I have added relevant tests.~~ (shouldn't be required with an example)
> adds panic hook example

- Cargo.toml
This crate's MSRV is 1.56.1. But it is not declared as package metadata.
This PR sets [`rust-version`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) metadata to `Cargo.toml` so that Clippy can run checks considering MSRV and users can check MSRV of their packages with tools such as [cargo-msrv](https://github.com/foresterre/cargo-msrv).
I checked `cargo check` results and unit tests passed.
> chore: explicitly set MSRV to 1.56.1 in Cargo.toml

- src/buffer.rs
- src/layout.rs
- src/style.rs
- src/text.rs
- src/widgets/block.rs
- src/widgets/list.rs
- src/widgets/table.rs
`clippy` included in the last version of rust is complaining about missing `Eq` derive. This PR adds them.
> chore: fix clippy warnings
