- .travis.yml
- Makefile
- examples/barchart.rs
- examples/block.rs
- examples/canvas.rs
- examples/chart.rs
- examples/demo.rs
- examples/gauge.rs
- examples/list.rs
- examples/paragraph.rs
- examples/rustbox.rs
- examples/sparkline.rs
- examples/table.rs
- examples/tabs.rs
- scripts/travis/before_script.sh
- scripts/travis/script.sh
- src/backend/rustbox.rs
- src/backend/termion.rs
- src/layout.rs
- src/terminal.rs
- src/widgets/barchart.rs
- src/widgets/canvas/mod.rs
- src/widgets/chart.rs
- src/widgets/gauge.rs
- src/widgets/list.rs
- src/widgets/paragraph.rs
- src/widgets/table.rs
- src/widgets/tabs.rs
* Add lint stage
* Fix rustfmt and clippy errors
* Refactor Makefile install rule
> Lint integration

- examples/barchart.rs
- examples/block.rs
- examples/canvas.rs
- examples/chart.rs
- examples/custom_widget.rs
- examples/demo.rs
- examples/gauge.rs
- examples/list.rs
- examples/paragraph.rs
- examples/sparkline.rs
- examples/table.rs
- examples/tabs.rs
- src/backend/mod.rs
- src/backend/termion.rs
> Mouse support

- examples/canvas.rs
- src/layout.rs
- src/widgets/barchart.rs
- src/widgets/canvas/mod.rs
- src/widgets/chart.rs
- src/widgets/mod.rs
- src/widgets/sparkline.rs
These are just some minor adjustments that don't change the logic of the library.
Mostly guided by clippy.
> Minor codestyle fixes

- Cargo.toml
- examples/user_input.rs
> User input example

- src/backend/mod.rs
> Make AlternateScreenBackend public.

- CHANGELOG.md
- src/backend/mod.rs
- src/backend/termion.rs
> Termion backend

- src/buffer.rs
- Add tests for this behavior.
- Extend documentation of Buffer::pos_of and Buffer::index_of
- Clarify that the coordinates should be in global coordinate-space (rather than local).
- Document panics.
- Add examples.
Adding both tests and doctests for these conditions might be overkill, but I hope there might be value in having both. Tests can be extended with more edge cases later without muddying up the documentation, for example.
Please let me know if you think this is appropriate or not.
Fixes #4.
> BUG: Buffer::pos_of panics on inside-bounds index

- CHANGELOG.md
- examples/list.rs
- src/widgets/list.rs
> Fix list style

- Cargo.toml
- examples/layout.rs
- src/layout.rs
- src/lib.rs
> Fix layout

- CHANGELOG.md
- src/widgets/paragraph.rs
> Fix text wrapping

- CHANGELOG.md
- examples/table.rs
- src/layout.rs
> Render closure

- examples/barchart.rs
- examples/block.rs
- examples/canvas.rs
- examples/chart.rs
- examples/custom_widget.rs
- examples/demo.rs
- examples/gauge.rs
- examples/layout.rs
- examples/list.rs
- examples/paragraph.rs
- examples/rustbox.rs
- examples/sparkline.rs
- examples/table.rs
- examples/tabs.rs
- examples/user_input.rs
- src/layout.rs
- src/widgets/canvas/map.rs
- src/widgets/list.rs
Add an option to render a list bottom first
> List orientation

- examples/paragraph.rs
- src/widgets/paragraph.rs
> [widgets][paragraph]: Truncate long lines when wrap is false

- examples/gauge.rs
- src/buffer.rs
- src/widgets/gauge.rs
- tests/gauge.rs
I wanted to also change `Constraint` but it's a bit more complex (needs a Rational or a f64 with Hash and Eq), another time.
>  Gauge: use f64 internally and allow to set any f64 between 0 and 1 

- examples/barchart.rs
- examples/block.rs
- examples/canvas.rs
- examples/chart.rs
- examples/crossterm.rs
- examples/custom_widget.rs
- examples/demo.rs
- examples/gauge.rs
- examples/layout.rs
- examples/list.rs
- examples/paragraph.rs
- examples/rustbox.rs
- examples/sparkline.rs
- examples/table.rs
- examples/tabs.rs
- examples/user_input.rs
- src/lib.rs
- src/terminal.rs
- tests/gauge.rs
That's one way of handling #99 . Please review.
cc @dotdash
> Frame: provide consistent size for rendering

- src/buffer.rs
- src/terminal.rs
- tests/paragraph.rs
Waits for: https://github.com/fdehau/tui-rs/pull/103
> Buffer: double width handling

- Cargo.toml
- src/backend/crossterm.rs
Waiting for https://github.com/TimonPost/crossterm/pull/78
> feat: handle crossterm errors

- src/buffer.rs
Coordinates returned by Buffer::pos_of were interpreted as local coordinates
while they were global. This was resulting in panics due to out of bounds
accesses. Interpreting the coordinates as global and using correct offsets
when computing the new index within the buffer for each cell fix the issue.
Fix #137
> Fix Buffer::merge

- CHANGELOG.md
fix the render of title in CHANFELOG
> fix typo of CHANFELOG

- README.md
> Fix a deadlink

- src/widgets/sparkline.rs
> Fix sparkline panic when max is zero

- examples/table.rs
- src/widgets/canvas/line.rs
- src/widgets/canvas/map.rs
- src/widgets/canvas/mod.rs
- src/widgets/canvas/points.rs
- src/widgets/canvas/rectangle.rs
- src/widgets/reflow.rs
Just silencing some Clippy warnings.
> Use dyn for boxed trait objects.

- src/layout.rs
This adds support for margins to be either vertical or horizontal, or
both.
> Make margins be vertical or horizontal

- README.md
Thanks very much for this library! :)
> docs(readme): add bandwhich to "apps using tui"

- src/widgets/chart.rs
- src/widgets/mod.rs
Closes #73
This commit only adds support for linecharts for the braille marker.
> Add linechart support

- README.md
Creator of https://github.com/cjbassi/gotop ported it over to Rust and is now being actively maintained at https://github.com/cjbassi/ytop. A great system monitor using TUI.
> add ytop to apps using

- README.md
Closes: #235 
Adds bottom as another application using tui-rs.
> Add bottom to the "apps using tui" list

- Cargo.toml
- examples/barchart.rs
- examples/block.rs
- examples/canvas.rs
- examples/chart.rs
- examples/crossterm_demo.rs
- examples/curses_demo.rs
- examples/custom_widget.rs
- examples/gauge.rs
- examples/layout.rs
- examples/list.rs
- examples/paragraph.rs
- examples/rustbox_demo.rs
- examples/sparkline.rs
- examples/table.rs
- examples/tabs.rs
- examples/termion_demo.rs
- examples/user_input.rs
- src/backend/rustbox.rs
- src/backend/termion.rs
- src/terminal.rs
* Remove log, stderrlog, structopt
* Add argh
> chore: remove unecessary dependencies

- src/symbols.rs
- src/widgets/block.rs
Add a new style of line and use a struct to avoir duplication of
matching
> Add "thick" lines and line::Set struct

- README.md
Thanks for the cool library! 🚀
> doc: Add kmon to 'apps using tui' in README

- Cargo.toml
this fixes #250 because crossterm `0.17.3` has a fix for the resize/size issue
> upgrade crossterm-rs dependency

- examples/crossterm_demo.rs
* avoid stacking events
* ensure tick events are sent at the given tick rate (and not everytime a key is pressed).
> fix(examples): improve input handling in crossterm demo

- README.md
Desed is new application that is using tui-rs. It's debugger for sed with all the things like stepping, setting breakpoints and examining runtime state.
It passed 500 github stars, so I think it's big and popular enough to be added to the list in readme.
> Add desed to list of apps using tui?

- README.md
Hi! I'm new to rust and [rust-sadari-cl](https://github.com/24seconds/rust-sadari-cli) is my first rust toy project.
This is cli base game, inspired by [Ghost-leg](https://en.wikipedia.org/wiki/Ghost_Leg) - sadari or Amidakuji in other words -
I choosed tui-rs to draw widgets in terminal and I really learned a lot from tui-rs code!
Thanks for amazing work :D
> Add rust-sadari-cli in `Apps using tui` section

- src/buffer.rs
> fix(buffer): ignore zero-width graphemes

- CHANGELOG.md
- Cargo.toml
- src/style.rs
* Add serde as an optional dependency.
* Add feature-gated derives to Color, Modifier and Style.
Fixes #292
> feat(style): add support to serialize and deserialize Style using serde

- README.md
Hey @fdehau,
I created another app using your cool library. It was really fun implementing a treemap using the infrastructure you created.
Thanks again for this library!
> Add diskonaut to "apps using tui"

- src/style.rs
Almost had need for this during the highlight style implementation, but avoided it in the end since `style` remained `Style` instead of `StyleDiff`.
In any case, I figured implementing this acted as a good exercise for just what a specific `StyleDiff` should mean in regards to what it does when it's applied (especially in relation to what modifiers get applied, if a `StyleDiff` specifies all `modifier`, `add_modifier` and `sub_modifier` with various degrees of overlap).
The PR changes the existing semantics in this regard by making the order in which modifiers are defined important (`modifier` overrides existing add/remove details and `add`/`remove` build on top of the last `modifier` while avoiding overlap between each other).
Even if the `patch` functionality wasn't needed, I feel …
> Implement `patch` between two `StyleDiff`

- README.md
Would be awesome if you could add my app to the list, thanks!
https://github.com/tarkah/tickrs
> add tickrs to apps using tui

- src/buffer.rs
- src/text.rs
- src/widgets/barchart.rs
- src/widgets/chart.rs
Unrelated to my other PR and is just stylistic, but I thought it was a little more Rust-y to use things like `max` and `sum`.
Pick and choose which changes you like I suppose (if any) :)
> Clean up some folds

- README.md
Thanks for the crate! Was very helpful in building the [rusty-krab-manager](https://github.com/aryakaul/rusty-krab-manager) :)
> add RKM to readme

- src/buffer.rs
- src/widgets/chart.rs
- tests/widgets_chart.rs
Make sure the style of the graphed data does not leak to the axis titles and the legend.
> Chart style

- src/style.rs
> Style reset

- src/widgets/reflow.rs
- tests/widgets_paragraph.rs
> Fix mishandling of NBSP with wrap turned on

- README.md
Thanks for this awesome library!
gping: https:.//github.com/orf/gping/
> Add gping to the lists of apps using tui

- Makefile.toml
Really cool project. I use it internally :)
I saw that the windows examples task i not implemented.
So i played with it a bit to make it work.
I couldn't test it on windows (need your help if possible) but on linux it works and its same code now (no need for 2 different tasks).
Tell me what you think?
> Make examples available for all platforms

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- CONTRIBUTING.md
* Improve issue templates and make them mandatory.
* Improve CONTRIBUTING.md.
* Add template for pull requests.
> chore: improve contributing guidelines

- README.md
Links now include the fully qualified domain as well as the version.
This will make them work in docs.rs and make sure readers are looking at code which is consistent with the latest version available.
Fixes #370
> chore: update links to examples in README

- README.md
`xplr` is a hackable TUI file explorer.
> Add xplr to the "apps using tui" list

- src/backend/rustbox.rs
- src/widgets/gauge.rs
Fix new Clippy warnings which were enabled by default in the latest Rust stable release.
> chore: fix clippy warnings

- README.md
This PR adds a link to a minesweeping game I wrote using `tui-rs`.
> chore: add minesweep to list of apps using tui-rs

- src/widgets/clear.rs
Clarify usage of `Clear`.
Close #476
> doc(widgets/clear): clarify usage of clear

- README.md
> Add battleship.rs

- Cargo.toml
- src/lib.rs
> chore: bump crossterm to 0.20

- CHANGELOG.md
- Cargo.toml
- README.md
- src/lib.rs
> Release v0.16.0

- README.md
I've just added my application [termscp](https://github.com/veeso/termscp) to apps using tui.
None
> termscp in README: 'Apps using tui'

- README.md
My `adsb_deku/radar` application uses tui, using the Table and Canvas to show
information and plot airplanes on a latitude/longitude coordinates map.
Commit adds this example to the `README.md`
N/A
> Add `adsb_deku/radar` to apps using `tui`

- README.md
Add [hoard](https://github.com/Hyde46/hoard) to list of projects using `tui`
> Add `hoard` to list of projects using tui

- .github/workflows/ci.yml
- Cargo.toml
- README.md
* Bump MSRV to 1.56.1
* Migrate to edition 2021
> feat!: bump MSRV to 1.56.1 and migrate to edition 2021

- CHANGELOG.md
- Cargo.toml
- README.md
- src/lib.rs
Release `v0.17.0` of the crate.
> Release v0.17.0

- src/widgets/reflow.rs
> fix: make ci

- CHANGELOG.md
- Cargo.toml
- README.md
- src/lib.rs
> Release v0.18.0

- README.md
Closes #610 
Closes #605
Closes #600 
Closes #590 
Closes #586
Closes #572 
Closes #580
> chore: add more apps using `tui` to the README

- .github/workflows/ci.yml
> chore(ci): bump cargo-make to v0.35.16

- Cargo.toml
[changelog](https://github.com/crossterm-rs/crossterm/blob/master/CHANGELOG.md)
Ran `cargo make run-examples`
> chore: bump crossterm to v0.25

- CHANGELOG.md
- Cargo.toml
- README.md
- src/lib.rs
> Release v0.19.0

- README.md
> chore: add apps using `tui`

- src/layout.rs
Just fix a small typo in the doc comment for `Rectangle`.
> Fix typo in layout.rs
